package com.enspy26.gi.database_agence_voyage.enums;

public enum Amenities {
  WIFI,
  AC,
  USB,
  SNACKS,
  BEVERAGES,
  POWER_OUTLETS,
  ENTERTAINMENT,
  COMFORTABLE_SEATS,
  RESTROOMS,
  LUGGAGE_STORAGE,
  CHILD_SEATS,
  PET_FRIENDLY,
  AIRPORT_PICKUP,
  AIRPORT_DROP_OFF,
  MEAL_SERVICE,
  ONBOARD_GUIDE,
  SEAT_SELECTION,
  GROUP_DISCOUNTS,
  LATE_CHECK_IN,
  LATE_CHECK_OUT
}
