package com.enspy26.gi.database_agence_voyage.enums;

public enum StatutHistorique {
  ANNULER_PAR_AGENCE_APRES_RESERVATION,
  ANNULER_PAR_USAGER_APRES_RESERVATION,
  ANNULER_PAR_AGENCE_APRES_CONFIRMATION,
  ANNULER_PAR_USAGER_APRES_CONFIRMATION,
  VALIDER
}
